/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerInventoryRouteImport } from './routes/seller.inventory'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerShopRouteImport } from './routes/seller.shop'
import { Route as SellerQrIdRouteImport } from './routes/seller.qr.$id'
import { Route as ApiPublicMgSplatRouteImport } from './routes/api/public/mg.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerInventoryRoute = SellerInventoryRouteImport.update({
  id: '/seller/inventory',
  path: '/seller/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerShopRoute = SellerShopRouteImport.update({
  id: '/seller/shop',
  path: '/seller/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerQrIdRoute = SellerQrIdRouteImport.update({
  id: '/seller/qr/$id',
  path: '/seller/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMgSplatRoute = ApiPublicMgSplatRouteImport.update({
  id: '/api/public/mg/$',
  path: '/api/public/mg/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/seller/inventory': typeof SellerInventoryRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/shop': typeof SellerShopRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/seller/qr/$id': typeof SellerQrIdRoute
  '/api/public/mg/$': typeof ApiPublicMgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/seller/inventory': typeof SellerInventoryRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/shop': typeof SellerShopRoute
  '/orders': typeof OrdersIndexRoute
  '/seller': typeof SellerIndexRoute
  '/seller/qr/$id': typeof SellerQrIdRoute
  '/api/public/mg/$': typeof ApiPublicMgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/seller/inventory': typeof SellerInventoryRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/shop': typeof SellerShopRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/seller/qr/$id': typeof SellerQrIdRoute
  '/api/public/mg/$': typeof ApiPublicMgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/search'
    | '/checkout/$id'
    | '/listing/$id'
    | '/orders/$id'
    | '/seller/inventory'
    | '/seller/orders'
    | '/seller/shop'
    | '/orders/'
    | '/seller/'
    | '/seller/qr/$id'
    | '/api/public/mg/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/search'
    | '/checkout/$id'
    | '/listing/$id'
    | '/orders/$id'
    | '/seller/inventory'
    | '/seller/orders'
    | '/seller/shop'
    | '/orders'
    | '/seller'
    | '/seller/qr/$id'
    | '/api/public/mg/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/search'
    | '/checkout/$id'
    | '/listing/$id'
    | '/orders/$id'
    | '/seller/inventory'
    | '/seller/orders'
    | '/seller/shop'
    | '/orders/'
    | '/seller/'
    | '/seller/qr/$id'
    | '/api/public/mg/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ListingIdRoute: typeof ListingIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  SellerInventoryRoute: typeof SellerInventoryRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerShopRoute: typeof SellerShopRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerQrIdRoute: typeof SellerQrIdRoute
  ApiPublicMgSplatRoute: typeof ApiPublicMgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/inventory': {
      id: '/seller/inventory'
      path: '/seller/inventory'
      fullPath: '/seller/inventory'
      preLoaderRoute: typeof SellerInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/shop': {
      id: '/seller/shop'
      path: '/seller/shop'
      fullPath: '/seller/shop'
      preLoaderRoute: typeof SellerShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/qr/$id': {
      id: '/seller/qr/$id'
      path: '/seller/qr/$id'
      fullPath: '/seller/qr/$id'
      preLoaderRoute: typeof SellerQrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mg/$': {
      id: '/api/public/mg/$'
      path: '/api/public/mg/$'
      fullPath: '/api/public/mg/$'
      preLoaderRoute: typeof ApiPublicMgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ListingIdRoute: ListingIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  SellerInventoryRoute: SellerInventoryRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerShopRoute: SellerShopRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerQrIdRoute: SellerQrIdRoute,
  ApiPublicMgSplatRoute: ApiPublicMgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
