/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as TrustguardRouteImport } from './routes/trustguard'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustguardRoute = TrustguardRouteImport.update({
  id: '/trustguard',
  path: '/trustguard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seller': typeof SellerRoute
  '/trustguard': typeof TrustguardRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seller': typeof SellerRoute
  '/trustguard': typeof TrustguardRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seller': typeof SellerRoute
  '/trustguard': typeof TrustguardRoute
  '/listing/$slug': typeof ListingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seller' | '/trustguard' | '/listing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seller' | '/trustguard' | '/listing/$slug'
  id: '__root__' | '/' | '/seller' | '/trustguard' | '/listing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SellerRoute: typeof SellerRoute
  TrustguardRoute: typeof TrustguardRoute
  ListingSlugRoute: typeof ListingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trustguard': {
      id: '/trustguard'
      path: '/trustguard'
      fullPath: '/trustguard'
      preLoaderRoute: typeof TrustguardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SellerRoute: SellerRoute,
  TrustguardRoute: TrustguardRoute,
  ListingSlugRoute: ListingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
