// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnfqfcwnfmfcgtsiexnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZnFmY3duZm1mY2d0c2lleG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyMDA2NzksImV4cCI6MjEwMjc3NjY3OX0.zHR1AktkOPv4JiwNQbIbpDlLfdqUWfDb4jcd9u92Xv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});